version: "3"

services:
  lovemint-backend-django:
    container_name: lovemint_django_backend
    restart: always
    build:
      context: .
      dockerfile: deployments/Dockerfile
      args:
        PROJECT: lovemint_django_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
        - db
        - redis
  db:
    image: mdillon/postgis:10
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
volumes:
  pgdata:
