# Generated by Django 3.2.9 on 2021-11-28 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.file_path)),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to=user.models.resize_file_path)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=8)),
                ('description_text', models.CharField(blank=True, max_length=128, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, max_length=512, null=True, srid=4326)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-id',),
            },
        ),
    ]
